# Generated by Django 3.1.4 on 2020-12-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201210_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
