# Generated by Django 3.1.4 on 2020-12-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201211_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date_edited',
            new_name='updated_at',
        ),
    ]
